[package]
org = "thisarug"
name = "prettify"
version = "1.0.0-SNAPSHOT"
authors = ["Thisaru Guruge (@ThisaruGuruge)"]
repository = "https://github.com/ThisaruGuruge/prettify"
license = ["Apache-2.0"]
distribution = "2201.0.0"
keywords = ["json", "pretty", "print", "json print", "pretty-print", "prettify", "prettify-json"]

[build-options]
observabilityIncluded = true
