name: "Build"

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Master Branch Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@master
              with:
                  args:
                      test --test-report

            - name: Code Coverage Repository
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
