name: "Pull Request Build"

on: pull_request

jobs:
    ubuntu-build:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@master
              with:
                  args:
                      pack --with-tests --code-coverage --coverage-format=xml

            - name: Code Coverage Repository
              uses: codecov/codecov-action@v2
